mod 'puppet/nginx', '1.0.0'
mod 'puppetlabs/concat'
mod 'puppetlabs/translate', '1.1.0'
mod 'puppetlabs/stdlib'
mod 'samuelson/dockeragent'
mod 'puppetlabs/docker', '3.1.0'
mod 'puppetlabs/apt'
mod 'puppetlabs/powershell'
mod 'puppetlabs/reboot'
mod 'puppetlabs/southalc-podman'
mod 'puppetlabs/selinux_core'
